GET http://localhost:3000/states/
###
GET http://localhost:3000/states/8/
###
POST http://localhost:3000/districts/
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###
GET http://localhost:3000/districts/55/
###
DELETE http://localhost:3000/districts/:districtId/
###
PUT http://localhost:3000/districts/:districtId/
Content-Type: application/json
 
{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###
GET http://localhost:3000/states/5/stats/
###
GET http://localhost:3000/districts/50/details/
Footer
© 2023 GitHub, Inc.
Footer navigation

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

